### ISSUE TITLE
Build failed on flutter v2.2.3 (latest stable)

### ISSUE THREAD

**Issue by iDoka** [persello/azsphere-obd-app#5] opened 2021-08-27 17:32 UTC
I use flutter v2.2.3 (latest stable) and it seems 2 years ago flutter was different (syntax or so - IDK),
may be if it has simple solution to fix build (I hope it might be fixed building options like `--std-c99` for `gcc` or similar, but I'm not so close familiar with dart and flutter technology to fix it by myself):

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] Connected device (2 available)
```

```
$ flutter run

Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...

lib/classes/fuel.g.dart:9:7: Error: The non-abstract class 'FuelAdapter' is missing implementations for these members:
 - TypeAdapter.typeId                                                  
Try to either                                                          
 - provide an implementation,                                          
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                      
 - provide a 'noSuchMethod' implementation.                            
                                                                       
class FuelAdapter extends TypeAdapter<Fuel> {                          
      ^^^^^^^^^^^                                                      
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/hive-1.4.4+1/lib/src/registry/type_adapter.dart:7:11: Context: 'TypeAdapter.typeId' is defined here.
  int get typeId;                                                      
          ^^^^^^                                                        
lib/classes/vehicle.g.dart:9:7: Error: The non-abstract class 'VehicleAdapter' is missing implementations for these members:
 - TypeAdapter.typeId                                                  
Try to either                                                          
 - provide an implementation,                                          
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                      
 - provide a 'noSuchMethod' implementation.                            
                                                                       
class VehicleAdapter extends TypeAdapter<Vehicle> {                    
      ^^^^^^^^^^^^^^                                                    
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/hive-1.4.4+1/lib/src/registry/type_adapter.dart:7:11: Context: 'TypeAdapter.typeId' is defined here.
  int get typeId;                                                      
          ^^^^^^                                                        
lib/classes/vehicle.g.dart:48:7: Error: The non-abstract class 'RemoteFileAdapter' is missing implementations for these members:
 - TypeAdapter.typeId                                                  
Try to either                                                          
 - provide an implementation,                                          
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                      
 - provide a 'noSuchMethod' implementation.                            
                                                                       
class RemoteFileAdapter extends TypeAdapter<RemoteFile> {              
      ^^^^^^^^^^^^^^^^^                                                
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/hive-1.4.4+1/lib/src/registry/type_adapter.dart:7:11: Context: 'TypeAdapter.typeId' is defined here.
  int get typeId;                                                      
          ^^^^^^                                                        
lib/globals.g.dart:9:7: Error: The non-abstract class 'MapViewSettingsDataAdapter' is missing implementations for these members:
 - TypeAdapter.typeId                                                  
Try to either                                                          
 - provide an implementation,                                          
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                      
 - provide a 'noSuchMethod' implementation.                            
                                                                       
class MapViewSettingsDataAdapter extends TypeAdapter<MapViewSettingsData> {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^                                        
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/hive-1.4.4+1/lib/src/registry/type_adapter.dart:7:11: Context: 'TypeAdapter.typeId' is defined here.
  int get typeId;                                                      
          ^^^^^^                                                        
lib/classes/logdata.g.dart:9:7: Error: The non-abstract class 'RawLogItemTypeAdapter' is missing implementations for these members:
 - TypeAdapter.typeId                                                  
Try to either                                                          
 - provide an implementation,                                          
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                      
 - provide a 'noSuchMethod' implementation.                            
                                                                       
class RawLogItemTypeAdapter extends TypeAdapter<RawLogItemType> {      
      ^^^^^^^^^^^^^^^^^^^^^                                            
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/hive-1.4.4+1/lib/src/registry/type_adapter.dart:7:11: Context: 'TypeAdapter.typeId' is defined here.
  int get typeId;                                                      
          ^^^^^^                                                        
lib/classes/logdata.g.dart:100:7: Error: The non-abstract class 'LogSessionAdapter' is missing implementations for these members:
 - TypeAdapter.typeId                                                  
Try to either                                                          
 - provide an implementation,                                          
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                      
 - provide a 'noSuchMethod' implementation.                            
                                                                       
class LogSessionAdapter extends TypeAdapter<LogSession> {              
      ^^^^^^^^^^^^^^^^^                                                
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/hive-1.4.4+1/lib/src/registry/type_adapter.dart:7:11: Context: 'TypeAdapter.typeId' is defined here.
  int get typeId;                                                      
          ^^^^^^                                                        
lib/classes/logdata.g.dart:129:7: Error: The non-abstract class 'RawTimedItemAdapter' is missing implementations for these members:
 - TypeAdapter.typeId                                                  
Try to either                                                          
 - provide an implementation,                                          
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                      
 - provide a 'noSuchMethod' implementation.                            
                                                                       
class RawTimedItemAdapter extends TypeAdapter<RawTimedItem> {          
      ^^^^^^^^^^^^^^^^^^^                                              
/opt/flutter/.pub-cache/hosted/pub.dartlang.org/hive-1.4.4+1/lib/src/registry/type_adapter.dart:7:11: Context: 'TypeAdapter.typeId' is defined here.
  int get typeId;                                                      
          ^^^^^^                                                        
lib/main.dart:33:23: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.                            
  Hive.registerAdapter(FuelAdapter(), HIVE_FUEL_ADAPTER_ID);            
                      ^                                                
lib/main.dart:34:23: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.                            
  Hive.registerAdapter(VehicleAdapter(), HIVE_VEHICLE_ADAPTER_ID);      
                      ^                                                
lib/main.dart:35:23: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.                            
  Hive.registerAdapter(MapViewSettingsDataAdapter(), HIVE_MAP_VIEW_SETTINGS_ADAPTER_ID);
                      ^                                                
lib/main.dart:36:23: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.                            
  Hive.registerAdapter(RawLogItemTypeAdapter(), HIVE_RAW_LOG_ITEM_ADAPTER_ID);
                      ^                                                
lib/main.dart:37:23: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.                            
  Hive.registerAdapter(LogSessionAdapter(), HIVE_LOG_SESSION_ADAPTER_ID);
                      ^                                                
lib/main.dart:38:23: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.                            
  Hive.registerAdapter(RawTimedItemAdapter(), HIVE_RAW_TIMED_ITEM_ADAPTER_ID);
                      ^                                                
lib/main.dart:39:23: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.                            
  Hive.registerAdapter(RemoteFileAdapter(), HIVE_REMOTE_FILE_ADAPTER_ID);
                      ^                                                
lib/classes/vehicle.dart:19:62: Error: No named parameter with the name 'lazy'.
      storedVehicleData = await Hive.openBox('vehicle-data', lazy: true);
                                                             ^^^^      
                                                                       
                                                                       
FAILURE: Build failed with an exception.                                
                                                                       
* Where:                                                                
Script '/opt/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035
                                                                       
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebug'.              
> Process 'command '/opt/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                       
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                       
* Get more help at https://help.gradle.org                              
                                                                       
BUILD FAILED in 37s                                                    
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        38.5s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by persello** [comment] 2021-09-07 11:46
I have made some edits and I can confirm that the project now works on iOS. I don't have an android device nor a board for testing. Should be solved by #6. Try to build from that branch. If it works on Android, I'll close the issue and merge the pull request.

Please note that, at least on iOS, I see crashes on the "Map" tab. It's related to the new version Hive DB, and I can't investigate it right now.

**Comment by iDoka** [comment] 2021-09-07 12:27
Riccardo thanks for your great job!
Despite to several strings marked as `error` the app builded for android and even running:

```
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
ERROR: [TAG] Failed to resolve variable '${junit.version}'              
ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'     
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
Note: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.1+4/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+6/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /opt/flutter/.pub-cache/hosted/pub.dartlang.org/permission_handler-3.2.2/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        98.1s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...              1,649ms
```

In emulator:

![Screenshot from 2021-09-07 15-22-44](https://user-images.githubusercontent.com/4820969/132344368-37dd836f-e240-4156-ac5e-777e44654b0d.png)

**Comment by persello** [comment] 2021-09-07 12:29
Feel free to open other issues regarding crashes.

**Closed** 2021-09-07 12:29 UTC

**Comment by iDoka** [comment] 2021-09-07 12:30
PS:
at least one issue remaining in runtime:
```
E/flutter (11418): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: HiveError: You need to initialize Hive or provide a path to store the box.
E/flutter (11418): #0      BackendManager.open (package:hive/src/backend/vm/backend_manager.dart:16:7)
E/flutter (11418): #1      HiveImpl._openBox (package:hive/src/hive_impl.dart:106:30)
E/flutter (11418): #2      HiveImpl.openBox (package:hive/src/hive_impl.dart:145:18)
E/flutter (11418): #3      StoredSettings.getAppSettingsBox (package:azsphere_obd_app/globals.dart:53:30)
E/flutter (11418): #4      new StoredSettings (package:azsphere_obd_app/globals.dart:46:18)
E/flutter (11418): #5      MyApp.build (package:azsphere_obd_app/main.dart:67:23)
E/flutter (11418): #6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4648:28)
E/flutter (11418): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4574:15)
E/flutter (11418): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4267:5)
E/flutter (11418): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4553:5)
E/flutter (11418): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4548:5)
E/flutter (11418): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3611:14)
E/flutter (11418): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3363:18)
E/flutter (11418): #13     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1189:16)
E/flutter (11418): #14     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1159:5)
E/flutter (11418): #15     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1104:18)
E/flutter (11418): #16     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2535:19)
E/flutter (11418): #17     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1103:13)
E/flutter (11418): #18     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:937:7)
E/flutter (11418): #19     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:917:7)
E/flutter (11418): #20     _rootRun (dart:async/zone.dart:1346:47)      
E/flutter (11418): #21     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (11418): #22     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (11418): #23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (11418): #24     _rootRun (dart:async/zone.dart:1354:13)      
E/flutter (11418): #25     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (11418): #26     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
E/flutter (11418): #27     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (11418): #28     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (11418): #29     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (11418): #30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (11418):                                                      
```

**Comment by persello** [comment] 2021-09-07 12:31
That's what I was talking about, issues in HiveDB. That library changed very much since the time I last used it. I'll try to get on it as soon as I can.

**Comment by iDoka** [comment] 2021-09-07 12:38
I think I can start working with code right now (because app successful build and running) and I don't know will I use map functional or so.
According this reason the issues in HiveDB does'nt required fixing in high priority (indeed I think it should fix with very-very-very low priority).

And again much thanks for your help!
